'use strict';

var React         = require('react');
var Multiselect   = require('./../js/components/Multiselect.react');

window.React = React;

var App = React.createClass({
  render: function () {
    return (
      <div>
        <Multiselect list={this.getList()}
                     selectors={true}
                     checkedByDefault={[{value: "ES", title: "Espagne"}]}
                     filterPlaceholder={"Search a country"} />
      </div>
    );
  },
  getList: function() {
    return [
      {value: "FR", title: "France"},
      {value: "BE", title: "Belgique"},
      {value: "ES", title: "Espagne"},
      {value: "IT", title: "Italie"},
      {value: "DE", title: "Allemagne"},
      {value: "PT", title: "Portugal"},
      {value: "GB", title: "Royaume-Uni"},
      {value: "US", title: "États-Unis"},
      {value: "CA", title: "Canada"},
      {value: "BR", title: "Brésil"},
      {value: "CN", title: "Chine"},
      {value: "JP", title: "Japon"},
      {value: "WF", title: "Wallis et Futuna"},
      {value: "JM", title: "Jamaïque"},
      {value: "JO", title: "Jordanie"},
      {value: "WS", title: "Samoa"},
      {value: "JE", title: "Jersey"},
      {value: "GW", title: "Guinea-Bissau"},
      {value: "GU", title: "Guam"},
      {value: "GT", title: "Guatémala"},
      {value: "GS", title: "Géorgie du Sud-et-les Îles Sandwich du Sud"},
      {value: "GR", title: "Grèce"},
      {value: "GQ", title: "Guinée équatoriale"},
      {value: "GP", title: "Guadeloupe"},
      {value: "GY", title: "Guyane"},
      {value: "GG", title: "Guernesey"},
      {value: "GF", title: "Guyane française"},
      {value: "GE", title: "Géorgie"},
      {value: "GD", title: "Grenade"},
      {value: "GA", title: "Gabon"},
      {value: "GN", title: "Guinée"},
      {value: "GM", title: "Gambia (The)"},
      {value: "GL", title: "Groenland"},
      {value: "GI", title: "Gibraltar"},
      {value: "GH", title: "Ghana"},
      {value: "PR", title: "Porto Rico"},
      {value: "PS", title: "Palestine, Etat de"},
      {value: "PW", title: "Palaos"},
      {value: "PY", title: "Paraguay"},
      {value: "PA", title: "Panama"},
      {value: "PF", title: "Polynésie française"},
      {value: "PG", title: "Papouasie-Nouvelle-Guinée"},
      {value: "PE", title: "Pérou"},
      {value: "PK", title: "Pakistan"},
      {value: "PH", title: "Philippines"},
      {value: "PN", title: "Île Pitcairn"},
      {value: "PL", title: "Pologne"},
      {value: "PM", title: "Saint-Pierre-et-Miquelon"},
      {value: "ZM", title: "Zambie"},
      {value: "ZA", title: "Afrique du Sud"},
      {value: "ZW", title: "Zimbabwe"},
      {value: "ME", title: "Monténégro"},
      {value: "MD", title: "Moldova (the Republic of)"},
      {value: "MG", title: "Madagascar"},
      {value: "MF", title: "Saint Martin (French part)"},
      {value: "MA", title: "Maroc"},
      {value: "MC", title: "Monaco"},
      {value: "MM", title: "Myanmar"},
      {value: "ML", title: "Mali"},
      {value: "MO", title: "Macao"},
      {value: "MN", title: "Mongolie"},
      {value: "MH", title: "Îles Marshal"},
      {value: "MK", title: "Macedonia (the former Yugoslav Republic of)"},
      {value: "MU", title: "Maurice"},
      {value: "MT", title: "Malte"},
      {value: "MW", title: "Malawi"},
      {value: "MV", title: "Maldives"},
      {value: "MQ", title: "Martinique"},
      {value: "MP", title: "Îles Mariannes du Nord"},
      {value: "MS", title: "Montserrat"},
      {value: "MR", title: "Mauritanie"},
      {value: "MY", title: "Malaisie"},
      {value: "MX", title: "Mexique"},
      {value: "MZ", title: "Mozambique"},
      {value: "FI", title: "Finlande"},
      {value: "FJ", title: "Fidji"},
      {value: "FK", title: "Falkland Islands  [Malvinas]"},
      {value: "FM", title: "Micronesia (the Federated States of)"},
      {value: "FO", title: "Îles Féroé"},
      {value: "CK", title: "Îles Cook"},
      {value: "CI", title: "Côte d'Ivoire"},
      {value: "CH", title: "Suisse"},
      {value: "CO", title: "Colombie"},
      {value: "CM", title: "Cameroun"},
      {value: "CL", title: "Chili"},
      {value: "CC", title: "Îles Cocos"},
      {value: "CG", title: "Congo"},
      {value: "CF", title: "République centrafricaine"},
      {value: "CD", title: "Congo (the Democratic Republic of the)"},
      {value: "CZ", title: "République tchèque"},
      {value: "CY", title: "Chypre"},
      {value: "CX", title: "Île Christmas"},
      {value: "CR", title: "Costa Rica"},
      {value: "CW", title: "Curaçao"},
      {value: "CV", title: "Cap-Vert"},
      {value: "CU", title: "Cuba"},
      {value: "SZ", title: "Swaziland"},
      {value: "SY", title: "Syrie"},
      {value: "SX", title: "Sint Maarten (Dutch part)"},
      {value: "SS", title: "Soudan du Sud"},
      {value: "SR", title: "Suriname"},
      {value: "SV", title: "Salvador"},
      {value: "ST", title: "Sao Tomé-et-Principe"},
      {value: "SK", title: "Slovaquie"},
      {value: "SJ", title: "Île Jan Mayen"},
      {value: "SI", title: "Slovénie"},
      {value: "SH", title: "Saint Helena, Ascension and Tristan da Cunha"},
      {value: "SO", title: "Somalie"},
      {value: "SN", title: "Sénégal"},
      {value: "SM", title: "Saint-Marin"},
      {value: "SL", title: "Sierra Leone"},
      {value: "SC", title: "Seychelles"},
      {value: "SB", title: "Salomon"},
      {value: "SA", title: "Arabie Saoudite"},
      {value: "SG", title: "Singapour"},
      {value: "SE", title: "Suède"},
      {value: "SD", title: "Soudan"},
      {value: "YE", title: "Yémen"},
      {value: "YT", title: "Mayotte"},
      {value: "LB", title: "Liban"},
      {value: "LC", title: "Sainte-Lucie"},
      {value: "LA", title: "Laos"},
      {value: "LK", title: "Sri Lanka"},
      {value: "LI", title: "Liechtenstein"},
      {value: "LV", title: "Lettonie"},
      {value: "LT", title: "Lituanie"},
      {value: "LU", title: "Luxembourg"},
      {value: "LR", title: "Libéria"},
      {value: "LS", title: "Lesotho"},
      {value: "LY", title: "Libye"},
      {value: "VA", title: "Holy See  [Vatican City State]"},
      {value: "VC", title: "Saint-Vincent-et-les-Grenadines"},
      {value: "VE", title: "Venezuela"},
      {value: "VG", title: "Virgin Islands (British)"},
      {value: "IQ", title: "Irak"},
      {value: "VI", title: "Virgin Islands (U.S.)"},
      {value: "IS", title: "Islande"},
      {value: "IR", title: "Iran (the Islamic Republic of)"},
      {value: "VN", title: "Vietnam"},
      {value: "IM", title: "Île de Man"},
      {value: "IL", title: "Israël"},
      {value: "IO", title: "Territoire britannique de l'océan Indien"},
      {value: "IN", title: "Inde"},
      {value: "IE", title: "Irlande"},
      {value: "ID", title: "Indonésie"},
      {value: "BD", title: "Bangladesh"},
      {value: "BF", title: "Burkina Faso"},
      {value: "BG", title: "Bulgarie"},
      {value: "BA", title: "Bosnie-Herzégovine"},
      {value: "BB", title: "Barbade"},
      {value: "BL", title: "Saint Barthélemy"},
      {value: "BM", title: "Bermudes"},
      {value: "BN", title: "Brunei Darussalam"},
      {value: "BO", title: "Bolivie"},
      {value: "BH", title: "Bahrain"},
      {value: "BI", title: "Burundi"},
      {value: "BJ", title: "Bénin"},
      {value: "BT", title: "Bhoutan"},
      {value: "BV", title: "Île Bouvet"},
      {value: "BW", title: "Botswana"},
      {value: "BQ", title: "Bonaire, Saint Eustache et Saba"},
      {value: "BS", title: "Bahamas"},
      {value: "BY", title: "Biélorussie"},
      {value: "BZ", title: "Bélize"},
      {value: "RU", title: "Russie"},
      {value: "RW", title: "Rwanda"},
      {value: "RS", title: "Serbie"},
      {value: "RE", title: "Réunion, La"},
      {value: "RO", title: "Roumanie"},
      {value: "OM", title: "Oman"},
      {value: "HR", title: "Croatie"},
      {value: "HT", title: "Haïti"},
      {value: "HU", title: "Hongrie"},
      {value: "HK", title: "Hong Kong "},
      {value: "HN", title: "Honduras"},
      {value: "HM", title: "Îles Heard-et-MacDonald"},
      {value: "EH", title: "Sahara occidental"},
      {value: "EE", title: "Estonie"},
      {value: "EG", title: "Égypte"},
      {value: "EC", title: "Équateur"},
      {value: "ET", title: "Éthiopie"},
      {value: "ER", title: "Érythrée"},
      {value: "UY", title: "Uruguay"},
      {value: "UZ", title: "Ouzbékistan"},
      {value: "UM", title: "Îles mineures éloignées des États-Unis"},
      {value: "UG", title: "Ouganda"},
      {value: "UA", title: "Ukraine"},
      {value: "VU", title: "Vanuatu"},
      {value: "NI", title: "Nicaragua"},
      {value: "NL", title: "Pays-Bas"},
      {value: "NO", title: "Norvège"},
      {value: "NA", title: "Namibie"},
      {value: "NC", title: "Nouvelle-Calédonie"},
      {value: "NE", title: "Niger"},
      {value: "NF", title: "Île Norfolk"},
      {value: "NG", title: "Nigeria"},
      {value: "NZ", title: "Nouvelle-Zélande"},
      {value: "NP", title: "Népal"},
      {value: "NR", title: "Nauru"},
      {value: "NU", title: "Niue"},
      {value: "KG", title: "Kirghizistan"},
      {value: "KE", title: "Kenya"},
      {value: "KI", title: "Kiribati"},
      {value: "KH", title: "Cambodge"},
      {value: "KN", title: "Saint-Christophe-et-Niévès"},
      {value: "KM", title: "Comores"},
      {value: "KR", title: "Korea (the Republic of)"},
      {value: "KP", title: "Korea (the Democratic People's Republic of)"},
      {value: "KW", title: "Koweït"},
      {value: "KZ", title: "Kazakhstan"},
      {value: "KY", title: "Îles Caïmans"},
      {value: "DO", title: "République dominicaine"},
      {value: "DM", title: "Dominique"},
      {value: "DJ", title: "Djibouti"},
      {value: "DK", title: "Danemark"},
      {value: "DZ", title: "Algérie"},
      {value: "TZ", title: "Tanzanie"},
      {value: "TV", title: "Tuvalu"},
      {value: "TW", title: "Taiwan (Province of China)"},
      {value: "TT", title: "Trinidad et Tobago"},
      {value: "TR", title: "Turquie"},
      {value: "TN", title: "Tunisie"},
      {value: "TO", title: "Tonga"},
      {value: "TL", title: "Timor-Leste"},
      {value: "TM", title: "Turkménistan"},
      {value: "TJ", title: "Tadjikistan"},
      {value: "TK", title: "Tokelau"},
      {value: "TH", title: "Thaïlande"},
      {value: "TF", title: "Terres australes et antarctiques françaises"},
      {value: "TG", title: "Togo"},
      {value: "TD", title: "Tchad"},
      {value: "TC", title: "Îles Turques-et-Caïques"},
      {value: "AE", title: "Émirats arabes unis"},
      {value: "AD", title: "Andorre"},
      {value: "AG", title: "Antigua et Barbuda"},
      {value: "AF", title: "Afghanistan"},
      {value: "AI", title: "Anguilla"},
      {value: "AM", title: "Arménie"},
      {value: "AL", title: "Albanie"},
      {value: "AO", title: "Angola"},
      {value: "AQ", title: "Antarctique"},
      {value: "AS", title: "Samoa américaines"},
      {value: "AR", title: "Argentine"},
      {value: "AU", title: "Australie"},
      {value: "AT", title: "Autriche"},
      {value: "AW", title: "Aruba"},
      {value: "AX", title: "Îles Åland"},
      {value: "AZ", title: "Azerbaïdjan"},
      {value: "QA", title: "Qatar"}
    ];
  }
});

React.render(
  new App(),
  document.getElementById('react-multiselect')
);

